FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y libopencv-dev vim git curl wget cmake build-essential

RUN pip install trimesh==3.9.8 numpy==1.19.2 pyhocon==0.3.57  icecream==2.1.0 opencv-contrib-python==4.5.2.52 tqdm==4.50.2 scipy==1.7.0 PyMCubes==0.1.2 imageio==2.31.1 scikit-image==0.19.3 tensorboard==2.11.2 matplotlib==3.6

